// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfgkpmlesblvvyasamyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZ2twbWxlc2JsdnZ5YXNhbXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjA1NTgsImV4cCI6MjA1NTE5NjU1OH0.FTl_3EPy3idUK-JIZJO_raZAbvOrlypRgrN-F-XY8B8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);